name: CENPA-SDL

channels:
        - conda-forge
        - bioconda
        - default

dependencies:
        - python=3.6
        - numpy=1.*
        - scipy=1.*
        - pandas=0.*
        - matplotlib=2.*
        - snakemake=4.*
        - jupyter
        - unzip
        - seaborn

